language: go
go:
    - 1.8
before_script:
    - sudo apt-get update
    - sudo apt-get install python-pip
script:
    - go test -v
    - go build
    - sudo pip install shipa-ci && shipa-ci --app=canary --server=$SHIPASERVER --email=$SHIPAEMAIL --password=$SHIPAPASSWORD --verbose
env:
    global:
notifications:
    on_success: never
    on_failure: never
